### ISSUE TITLE
Failure on install

### ISSUE THREAD

**Issue by nicoplh** [naraesk/plasma-docker#1]
Hi, can you please provide all the components for a good install.

I've this error on the Cmake :

CMake Error at /usr/local/share/ECM/modules/ECMQueryQmake.cmake:30 (message):
  No qmake Qt5 binary found.  Can't check QT_INSTALL_PLUGINS as required
Call Stack (most recent call first):
  /usr/local/share/ECM/kde-modules/KDEInstallDirs.cmake:473 (query_qmake)
  CMakeLists.txt:11 (include)

**Comment by naraesk** [comment]
Thanks for reporting. Which distro do you use?

Seems like qmake is not installed. But as far as I know, qmake is installed with every qt installation, which you need obviously for running KDE.

**Comment by naraesk** [comment]
Please have a look at the new version, does it work for you?
If not, what is your build environment?

**Comment by thecyberd3m0n** [comment]
same error I've got while trying to install it. I can help
