### ISSUE TITLE
Can't see docker images

### ISSUE THREAD

**Issue by marcoYalo** [naraesk/plasma-docker#10]
Hi!!

I'm having trouble to see my docker images inside plasmoid although I already add a docker-compose file.

![plasma-docker_1](https://user-images.githubusercontent.com/61328626/77403382-cb70f400-6d75-11ea-82a5-eb75b4898b89.png)
![plasma-docker_2](https://user-images.githubusercontent.com/61328626/77403385-cc098a80-6d75-11ea-9295-c811d9b198d8.png)

I don't know what else I'm missing.

This is my System Information:

- Operating System: KDE neon 5.18
- KDE Plasma Version: 5.18.3
- KDE Frameworks Version: 5.68.0
- Qt Version: 5.14.1
- Kernel Version: 5.3.0-42-generic
- OS Type: 64-bit
- Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
- Memory: 15.3 GiB of RAM

Please contact me if you need more info.

Thanks in advance!!

**Comment by naraesk** [comment]
Thanks for reporting. Is the docker daemon running? The plasmoid does not check for this at the moment.

**Comment by marcoYalo** [comment]
Hi Naraesk!! Thansk for the fast reply!!

Yes, the deamon is running but still can't see my docker images.

![image](https://user-images.githubusercontent.com/61328626/77450215-98038900-6db8-11ea-878b-1afac92fd243.png)

For plasmoid installation, I ran the install.sh script. Add the plasmoid to my latte dock and load the docker-compose.yml file.

Thanks in advance!!

**Comment by naraesk** [comment]
Still can't reproduce this. Could you please check the following:

There should be a file `plasma-org.kde.plasma.desktop-appletsrc` in ~/.config (or something similar with -appletsrc). Search for the lines representing the widget, they should include something like

`[Containments][1][Applets][48][Configuration][General]
container={"service":"Integrations"\\,"dir":"/link/to/file/docker-compose.yml"}`

Does it exist?

**Comment by naraesk** [comment]
What's the output of the following command?

`docker-compose -f /link/to/docker-compose.yml ps --services`

You have to replace the argument with your path, of course. :)

**Comment by marcoYalo** [comment]
I install docker and use it without sudo and now is working.
Thanks naraesk!!!
