### ISSUE TITLE
Instaled but not visible

### ISSUE THREAD

**Issue by grekpg** [naraesk/plasma-docker#2]
I install widget from plasma install, kubuntu 18.04
any error but its not visible in widget lists

![obraz](https://user-images.githubusercontent.com/2538271/42420023-cad59994-82bf-11e8-8c52-f31e1f5f62ee.png)

![obraz](https://user-images.githubusercontent.com/2538271/42420030-f0e21720-82bf-11e8-9557-872b6e280cf4.png)

**Comment by naraesk** [comment]
Thanks for reporting. Please try to install it manually following the install instructions. AFAIK it is technically not possible to install the plasmoid using the "get hot new stuff" browser, but I'm not sure

**Comment by alexanderadam** [comment]
Where can someone find and activate the widget _after_ following the manual instructions?
Somehow I can't find it in any dialogue.

**Comment by naraesk** [comment]
No, it does not load automatically. Its a plasma widget ("Miniprogramm") and can be added just as any other plasma widget. You are familiar with adding plasma widgets, aren't you?

**Comment by alexanderadam** [comment]
Well, I tried to add it via "Add Widgets" but I can't find it in the list of possible Widgets.
Is there something that must be reloaded or so?

**Comment by naraesk** [comment]
Hm, it seems to work out of the box for most users, but since you are the second one with this issue there might be a problem. I'll have a look into it.

**Comment by naraesk** [comment]
Ok, was able to reproduce this with Kubuntu. The problem is that `qtpaths --install-prefix` does not work with Ubuntu. Not sure what is a more generic solution, but for the moment you can replace `qtpaths --install-prefix` with `/usr` in the cmake command.
