### ISSUE TITLE
Can't find Plasma Docker after install

### ISSUE THREAD

**Issue by thecyberd3m0n** [naraesk/plasma-docker#3]
I've installed Plasma Docker Control, but can't find it in widgets list.

![image](https://user-images.githubusercontent.com/6655915/61234072-74207b80-a732-11e9-8710-265628b90c21.png)

**Comment by naraesk** [comment]
Do you use Ubuntu?

**Comment by thecyberd3m0n** [comment]
Nope, KDE Neon

**Comment by naraesk** [comment]
Ok, what's the output of `kf5-config --prefix` on your system?

**Comment by naraesk** [comment]
Hm, that's the expected output. Will have a look at it, but it'll take a few days. 

Can you please post the output of the different make commands? It does not harm to run them again and reinstall the widget.

**Comment by thecyberd3m0n** [comment]
yes of course, let's stay in touch

**Comment by naraesk** [comment]
Oh, I just had a second look at your screenshot. Did you install the widget automatically vai the Plasma Add New Widget Dialog? This does not work, unfortunately. You have to install it manually following the installation instructions in the README.

**Comment by thecyberd3m0n** [comment]
yes, it was auto install

**Comment by naraesk** [comment]
Plasma Widgets can be QML only (no compilation) or a mixture of QML and C++ (needs compilation). This tool only supports the first kind of widgets, so as far as I know there is nothing I can do about that.

**Comment by thecyberd3m0n** [comment]
thanks for feedback, I didn't know how Plasma Widgets work in this situation
